# ASP.NET Core (.NET Framework with ReactJS)
# Build and test ASP.NET Core projects targeting the full .NET Framework.

name: $(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyy-MM-dd).$(BuildID)
trigger:
  branches:
    include: 
    - develop
    - master


variables: 
  AzP.ServiceConnectionName: 'in.lab'
  Terraform.backendServiceArm: 'in.lab'
  Terraform.backendAzureRmResourceGroupName: 'shared-bachlorgrupper'
  Terraform.backendAzureRmStorageAccountName: 'bachelorgrupperstorage'
  Terraform.backendAzureRmContainerName: 'gruppedemo'
  Terraform.Terraform.backendAzureRmKey: 'build.tfstate'
  Terraform.version: '0.12.12'

  ${{ if eq( variables['Build.SourceBranchName'], 'master') }}:
     ConfigBuild: 'Release'

  ${{ if ne( variables['Build.SourceBranchName'], 'master') }}:
     ConfigBuild: 'Debug'    

phases:
  - phase: Infrastructure
    queue:
      name: 'Private VS2019'
    steps:
    - task: CopyFiles@2
      displayName: Copy artifacts
      inputs:
        SourceFolder: Infrastructure
        contents: |
          **
          !.vsts-ci.yml
          !**/.git/**
          !**/.terraform/**
        targetFolder: $(Build.ArtifactStagingDirectory)/Infrastructure    
    
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform version: 0.12.12'
      inputs:
        terraformVersion: '$(Terraform.Version)'
        
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm init'
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/Infrastructure'
        commandOptions: '-no-color'
        backendServiceArm: '$(Terraform.backendServiceArm)'
        backendAzureRmResourceGroupName: '$(Terraform.backendAzureRmResourceGroupName)'
        backendAzureRmStorageAccountName: '$(Terraform.backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(Terraform.backendAzureRmContainerName)'
        backendAzureRmKey: '$(Terraform.backendAzureRmKey)'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: Validate Terraform configuration
      inputs:
        command: validate
        variables: |
          environment=dev
          release=release
        workingDirectory: '$(Build.ArtifactStagingDirectory)/Infrastructure'
      
    - task: DeleteFiles@1
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/Infrastructure'
        Contents: '.terraform'

    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/Infrastructure
        artifactName: Infrastructure
        artifactType: container

        
  - phase: Build
    displayName: Project Build And Publish
    queue: 
      name: 'Private VS2019'
      workspace:
        clean: outputs
    variables:
      BuildPlatform: 'any cpu'
      BuildConfiguration: '$(ConfigBuild)'
      IsPrerelease: True
    steps: 
    - task: DotNetCoreInstaller@0
      displayName: 'Install .NET Core sdk 3.0.100'
      inputs:
        version: 3.0.100

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 3.x'
      inputs:
        version: 3.x

    - task: DotNetCoreCLI@2
      displayName: restore    
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        nugetConfigPath: '$(Build.SourcesDirectory)/Bachelorprosjekt/Bachelorprosjekt/nuget.config'
        arguments: '-r win-x64' 

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*[Tt]est/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        arguments: '-r win-x64 --self-contained --no-restore --configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)/project" -f netcoreapp3.1'
        zipAfterPublish: True
        projects: '$(Build.SourcesDirectory)/Bachelorprosjekt/Bachelorprosjekt/Bachelorprosjekt.csproj'
        workingDirectory: '$(Build.SourcesDirectory)/Bachelorprosjekt'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Project Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/project'