export const CREATE_RESOURCES_PENDING = "CREATE_RESOURCES_PENDING";
export const CREATE_RESOURCES_FAILED = "CREATE_RESOURCES_FAILED";
export const CREATE_RESOURCES_SUCCEEDED = "CREATE_RESOURCES_SUCCEEDED";

export const READ_RESOURCES_PENDING = "READ_RESOURCES_PENDING";
export const READ_RESOURCES_FAILED = "READ_RESOURCES_FAILED";
export const READ_RESOURCES_SUCCEEDED = "READ_RESOURCES_SUCCEEDED";

export const UPDATE_RESOURCES_PENDING = "UPDATE_RESOURCES_PENDING";
export const UPDATE_RESOURCES_FAILED = "UPDATE_RESOURCES_FAILED";
export const UPDATE_RESOURCES_SUCCEEDED = "UPDATE_RESOURCES_SUCCEEDED";

export const DELETE_RESOURCES_PENDING = "DELETE_RESOURCES_PENDING";
export const DELETE_RESOURCES_FAILED = "DELETE_RESOURCES_FAILED";
export const DELETE_RESOURCES_SUCCEEDED = "DELETE_RESOURCES_SUCCEEDED";
