export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_USERS_SUCCEEDED = "GET_USERS_SUCCEEDED";

export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

export const GET_USER_GROUPS_PENDING = "GET_USER_GROUPS_PENDING";
export const GET_USER_GROUPS_FAILED = "GET_USER_GROUPS_FAILED";
export const GET_USER_GROUPS_SUCCEEDED = "GET_USER_GROUPS_SUCCEEDED";

export const GET_USER_SMART_LOCKS_PENDING = "GET_USER_SMART_LOCKS_PENDING";
export const GET_USER_SMART_LOCKS_FAILED = "GET_USER_SMART_LOCKS_FAILED";
export const GET_USER_SMART_LOCKS_SUCCEEDED = "GET_USER_SMART_LOCKS_SUCCEEDED";

export const GET_CURRENT_AUTHENTICATED_USER_PENDING =
  "GET_CURRENT_AUTHENTICATED_USER_PENDING";
export const GET_CURRENT_AUTHENTICATED_USER_FAILED =
  "GET_CURRENT_AUTHENTICATED_USER_FAILED";
export const GET_CURRENT_AUTHENTICATED_USER_SUCCEEDED =
  "GET_CURRENT_AUTHENTICATED_USER_SUCCEEDED";

export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const ADD_USER_SUCCEEDED = "ADD_USER_SUCCEEDED";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCEEDED = "UPDATE_USER_SUCCEEDED";

export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const DELETE_USER_SUCCEEDED = "DELETE_USER_SUCCEEDED";

export const GET_GROUPS_PENDING = "GET_GROUPS_PENDING";
export const GET_GROUPS_FAILED = "GET_GROUPS_FAILED";
export const GET_GROUPS_SUCCEEDED = "GET_GROUPS_SUCCEEDED";

export const GET_GROUP_PENDING = "GET_GROUP_PENDING";
export const GET_GROUP_FAILED = "GET_GROUP_FAILED";
export const GET_GROUP_SUCCEEDED = "GET_GROUP_SUCCEEDED";

export const GET_GROUP_USERS_PENDING = "GET_GROUP_USERS_PENDING";
export const GET_GROUP_USERS_FAILED = "GET_GROUP_USERS_FAILED";
export const GET_GROUP_USERS_SUCCEEDED = "GET_GROUP_USERS_SUCCEEDED";

export const GET_GROUP_SMART_LOCKS_PENDING = "GET_GROUP_SMART_LOCKS_PENDING";
export const GET_GROUP_SMART_LOCKS_FAILED = "GET_GROUP_SMART_LOCKS_FAILED";
export const GET_GROUP_SMART_LOCKS_SUCCEEDED =
  "GET_GROUP_SMART_LOCKS_SUCCEEDED";

export const ADD_GROUP_PENDING = "ADD_GROUP_PENDING";
export const ADD_GROUP_FAILED = "ADD_GROUP_FAILED";
export const ADD_GROUP_SUCCEEDED = "ADD_GROUP_SUCCEEDED";

export const UPDATE_GROUP_PENDING = "UPDATE_GROUP_PENDING";
export const UPDATE_GROUP_FAILED = "UPDATE_GROUP_FAILED";
export const UPDATE_GROUP_SUCCEEDED = "UPDATE_GROUP_SUCCEEDED";

export const DELETE_GROUP_PENDING = "DELETE_GROUP_PENDING";
export const DELETE_GROUP_FAILED = "DELETE_GROUP_FAILED";
export const DELETE_GROUP_SUCCEEDED = "DELETE_GROUP_SUCCEEDED";

export const SET_SELECTED_GROUP_ID = "SET_SELECTED_GROUP_ID";

export const OPEN_ADD_GROUP_DIALOG = "OPEN_ADD_GROUP_DIALOG";
export const CLOSE_ADD_GROUP_DIALOG = "CLOSE_ADD_GROUP_DIALOG";

export const OPEN_EDIT_GROUP_DIALOG = "OPEN_EDIT_GROUP_DIALOG";
export const CLOSE_EDIT_GROUP_DIALOG = "CLOSE_EDIT_GROUP_DIALOG";

export const OPEN_DELETE_GROUP_DIALOG = "OPEN_DELETE_GROUP_DIALOG";
export const CLOSE_DELETE_GROUP_DIALOG = "CLOSE_DELETE_GROUP_DIALOG";

export const GET_SMART_LOCKS_PENDING = "GET_SMART_LOCKS_PENDING";
export const GET_SMART_LOCKS_FAILED = "GET_SMART_LOCKS_FAILED";
export const GET_SMART_LOCKS_SUCCEEDED = "GET_SMART_LOCKS_SUCCEEDED";

export const GET_SMART_LOCK_PENDING = "GET_SMART_LOCK_PENDING";
export const GET_SMART_LOCK_FAILED = "GET_SMART_LOCK_FAILED";
export const GET_SMART_LOCK_SUCCEEDED = "GET_SMART_LOCK_SUCCEEDED";

export const GET_SMART_LOCK_USERS_PENDING = "GET_SMART_LOCK_USERS_PENDING";
export const GET_SMART_LOCK_USERS_FAILED = "GET_SMART_LOCK_USERS_FAILED";
export const GET_SMART_LOCK_USERS_SUCCEEDED = "GET_SMART_LOCK_USERS_SUCCEEDED";

export const GET_SMART_LOCK_GROUPS_PENDING = "GET_SMART_LOCK_GROUPS_PENDING";
export const GET_SMART_LOCK_GROUPS_FAILED = "GET_SMART_LOCK_GROUPS_FAILED";
export const GET_SMART_LOCK_GROUPS_SUCCEEDED =
  "GET_SMART_LOCK_GROUPS_SUCCEEDED";

export const ADD_SMART_LOCK_PENDING = "ADD_SMART_LOCK_PENDING";
export const ADD_SMART_LOCK_FAILED = "ADD_SMART_LOCK_FAILED";
export const ADD_SMART_LOCK_SUCCEEDED = "ADD_SMART_LOCK_SUCCEEDED";

export const ADD_SMART_LOCK_USER_PENDING = "ADD_SMART_LOCK_USER_PENDING";
export const ADD_SMART_LOCK_USER_FAILED = "ADD_SMART_LOCK_USER_FAILED";
export const ADD_SMART_LOCK_USER_SUCCEEDED = "ADD_SMART_LOCK_USER_SUCCEEDED";

export const ADD_SMART_LOCK_GROUP_PENDING = "ADD_SMART_LOCK_GROUP_PENDING";
export const ADD_SMART_LOCK_GROUP_FAILED = "ADD_SMART_LOCK_GROUP_FAILED";
export const ADD_SMART_LOCK_GROUP_SUCCEEDED = "ADD_SMART_LOCK_GROUP_SUCCEEDED";

export const UPDATE_SMART_LOCK_PENDING = "UPDATE_SMART_LOCK_PENDING";
export const UPDATE_SMART_LOCK_FAILED = "UPDATE_SMART_LOCK_FAILED";
export const UPDATE_SMART_LOCK_SUCCEEDED = "UPDATE_SMART_LOCK_SUCCEEDED";

export const DELETE_SMART_LOCK_PENDING = "DELETE_SMART_LOCK_PENDING";
export const DELETE_SMART_LOCK_FAILED = "DELETE_SMART_LOCK_FAILED";
export const DELETE_SMART_LOCK_SUCCEEDED = "DELETE_SMART_LOCK_SUCCEEDED";

export const DELETE_SMART_LOCK_USER_PENDING = "DELETE_SMART_LOCK_USER_PENDING";
export const DELETE_SMART_LOCK_USER_FAILED = "DELETE_SMART_LOCK_USER_FAILED";
export const DELETE_SMART_LOCK_USER_SUCCEEDED =
  "DELETE_SMART_LOCK_USER_SUCCEEDED";

export const DELETE_SMART_LOCK_GROUP_PENDING =
  "DELETE_SMART_LOCK_GROUP_PENDING";
export const DELETE_SMART_LOCK_GROUP_FAILED = "DELETE_SMART_LOCK_GROUP_FAILED";
export const DELETE_SMART_LOCK_GROUP_SUCCEEDED =
  "DELETE_SMART_LOCK_GROUP_SUCCEEDED";

export const GET_AZURE_AD_USERS_PENDING = "GET_AZURE_AD_USERS_PENDING";
export const GET_AZURE_AD_USERS_FAILED = "GET_AZURE_AD_USERS_FAILED";
export const GET_AZURE_AD_USERS_SUCCEEDED = "GET_AZURE_AD_USERS_SUCCEEDED";

export const GET_AZURE_AD_USER_PENDING = "GET_AZURE_AD_USER_PENDING";
export const GET_AZURE_AD_USER_FAILED = "GET_AZURE_AD_USER_FAILED";
export const GET_AZURE_AD_USER_SUCCEEDED = "GET_AZURE_AD_USER_SUCCEEDED";

export const GET_AZURE_AD_USER_PHOTO_PENDING =
  "GET_AZURE_AD_USER_PHOTO_PENDING";
export const GET_AZURE_AD_USER_PHOTO_FAILED = "GET_AZURE_AD_USER_PHOTO_FAILED";
export const GET_AZURE_AD_USER_PHOTO_SUCCEEDED =
  "GET_AZURE_AD_USER_PHOTO_SUCCEEDED";

export const GET_AZURE_AD_USER_GROUPS_PENDING =
  "GET_AZURE_AD_USER_GROUPS_PENDING";
export const GET_AZURE_AD_USER_GROUPS_FAILED =
  "GET_AZURE_AD_USER_GROUPS_FAILED";
export const GET_AZURE_AD_USER_GROUPS_SUCCEEDED =
  "GET_AZURE_AD_USER_GROUPS_SUCCEEDED";

export const GET_AZURE_AD_GROUPS_PENDING = "GET_AZURE_AD_GROUPS_PENDING";
export const GET_AZURE_AD_GROUPS_FAILED = "GET_AZURE_AD_GROUPS_FAILED";
export const GET_AZURE_AD_GROUPS_SUCCEEDED = "GET_AZURE_AD_GROUPS_SUCCEEDED";

export const GET_AZURE_AD_GROUP_PENDING = "GET_AZURE_AD_GROUP_PENDING";
export const GET_AZURE_AD_GROUP_FAILED = "GET_AZURE_AD_GROUP_FAILED";
export const GET_AZURE_AD_GROUP_SUCCEEDED = "GET_AZURE_AD_GROUP_SUCCEEDED";

export const GET_AZURE_AD_GROUP_MEMBERS_PENDING =
  "GET_AZURE_AD_GROUP_MEMBERS_PENDING";
export const GET_AZURE_AD_GROUP_MEMBERS_FAILED =
  "GET_AZURE_AD_GROUP_MEMBERS_FAILED";
export const GET_AZURE_AD_GROUP_MEMBERS_SUCCEEDED =
  "GET_AZURE_AD_GROUP_MEMBERS_SUCCEEDED";
