export const USERS_RESOURCE_TYPE = "USERS";
export const USER_RESOURCE_TYPE = "USER";
export const USER_GROUPS_RESOURCE_TYPE = "USER_GROUPS";
export const USER_SMART_LOCKS_RESOURCE_TYPE = "USER_SMART_LOCKS";
export const CURRENT_AUTHENTICATED_USER_RESOURCE_TYPE =
  "CURRENT_AUTHENTICATED_USER";

export const GROUPS_RESOURCE_TYPE = "GROUPS";
export const GROUP_RESOURCE_TYPE = "GROUP";
export const GROUP_USERS_RESOURCE_TYPE = "GROUP_USERS";
export const GROUP_SMART_LOCKS_RESOURCE_TYPE = "GROUP_SMART_LOCKS";

export const SMART_LOCKS_RESOURCE_TYPE = "SMART_LOCKS";
export const SMART_LOCK_RESOURCE_TYPE = "SMART_LOCK";
export const SMART_LOCK_USERS_RESOURCE_TYPE = "SMART_LOCK_USERS";
export const SMART_LOCK_USER_RESOURCE_TYPE = "SMART_LOCK_USER";
export const SMART_LOCK_GROUPS_RESOURCE_TYPE = "SMART_LOCK_GROUPS";
export const SMART_LOCK_GROUP_RESOURCE_TYPE = "SMART_LOCK_GROUP";

export const AZURE_AD_USERS_RESOURCE_TYPE = "AZURE_AD_USERS";
export const AZURE_AD_USER_RESOURCE_TYPE = "AZURE_AD_USER";
export const AZURE_AD_USER_PHOTO_RESOURCE_TYPE = "AZURE_AD_USER_PHOTO";
export const AZURE_AD_USER_GROUPS_RESOURCE_TYPE = "AZURE_AD_USER_GROUPS";
export const AZURE_AD_GROUPS_RESOURCE_TYPE = "AZURE_AD_GROUPS";
export const AZURE_AD_GROUP_RESOURCE_TYPE = "AZURE_AD_GROUP";
export const AZURE_AD_GROUP_MEMBERS_RESOURCE_TYPE = "AZURE_AD_GROUP_MEMBERS";
