# ASP.net Core API Pipline

name: $(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyy-MM-dd).$(BuildID)
trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include:
    - api/*

variables: 
  Terraform.backendServiceArm: 'bacheloroppgaver-shared-services-dev-sc'
  Terraform.backendAzureRmResourceGroupName: 'stud-shared-dwe-rg'
  Terraform.backendAzureRmStorageAccountName: 'studshareddwesa'
  Terraform.backendAzureRmContainerName: 'gruppe5'
  Terraform.backendAzureRmKey: 'gruppe5Api.tfstate'
  Terraform.version: '0.12.21'

  ${{ if eq( variables['Build.SourceBranchName'], 'master') }}:
     ConfigBuild: 'Release'

  ${{ if ne( variables['Build.SourceBranchName'], 'master') }}:
     ConfigBuild: 'Debug'    

phases:
  - phase: Infrastructure
    queue:
      name: 'Private VS2019'
    steps:
    - task: CopyFiles@2
      displayName: Copy artifacts
      inputs:
        SourceFolder: api/Infrastructure
        contents: |
          **
          !.vsts-ci.yml
          !**/.git/**
          !**/.terraform/**
        targetFolder: $(Build.ArtifactStagingDirectory)/api/Infrastructure    
    
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform version: 0.12.12'
      inputs:
        terraformVersion: '$(Terraform.Version)'
        
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm init'
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/api/Infrastructure'
        commandOptions: '-no-color'
        backendServiceArm: '$(Terraform.backendServiceArm)'
        backendAzureRmResourceGroupName: '$(Terraform.backendAzureRmResourceGroupName)'
        backendAzureRmStorageAccountName: '$(Terraform.backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(Terraform.backendAzureRmContainerName)'
        backendAzureRmKey: '$(Terraform.backendAzureRmKey)'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: Validate Terraform configuration
      inputs:
        command: validate
        variables: |
          environment=dev
          release=release
        workingDirectory: '$(Build.ArtifactStagingDirectory)/api/Infrastructure'
      
    - task: DeleteFiles@1
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/api/Infrastructure'
        Contents: '.terraform'

    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/api/Infrastructure
        artifactName: Infrastructure
        artifactType: Container

        
