import axios from "axios";
import { getToken } from "./auth";

const http = axios.create({
  baseURL: "http://localhost:5000/api/",
  timeout: 10000,
  headers: { "X-Requested-With": "XMLHttpRequest" }
});

let authorizationHeader;

if (process.env.NODE_ENV === "test") {
  // Change this to a valid token to use in end to end test.
  // For the sake of simplicity you can copy the token from your browser console after a valid login
  authorizationHeader =
    "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiI5M2E1YzcyNi05ODNmLTRlOGMtYTMzMC1mMWIzNGUzZDY3NTIiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zNjAyZTQ5OC1mZDM0LTRhMWUtYTYxYi1iNDYzOWNlZWFmZmQvIiwiaWF0IjoxNTg4ODYwODkyLCJuYmYiOjE1ODg4NjA4OTIsImV4cCI6MTU4ODg2NDc5MiwiYWdlR3JvdXAiOiIzIiwiYWlvIjoiQVNRQTIvOFBBQUFBQW1mWTFyTE42MmplbHFFZGlpRFpDUGtUcCtrTEMxS0d2cmZsUmlWMjBHWT0iLCJhbXIiOlsicHdkIl0sImZhbWlseV9uYW1lIjoiQWJvIEFsa2hhaXIiLCJnaXZlbl9uYW1lIjoiTW9oYW1hZCIsImdyb3VwcyI6WyJmZTY1YTc2My0zMTg2LTRlMGUtYjBjNS0zYTMyMmE3MDllY2UiLCJiZjk4NDk1Mi0yZTc4LTQ3ZmEtOTIzOS1lZmVhNjRjN2YzMWIiLCJlMWYyZGY5My0yM2I2LTQ1ZWMtOWUyZi1hODQ1ZmNkMjVjZmYiLCI4YjRiNTM0NC05MDUwLTRmZDAtODU4Yi01YjkzMTI1MzQxYzkiLCI4NWJmZDAwNC04MTU0LTQ0YTMtYjZjNi0wMWRhNzYxMmM1YTciXSwiaXBhZGRyIjoiMzcuMTkxLjEyOC43OCIsIm5hbWUiOiJtb2hhbWFkIEFibyBBbGtoYWlyIiwibm9uY2UiOiJjMzgzMmNhMi03ZjcwLTQ0ZGUtYWFkMC1hNzdlNTg4MGVkZTciLCJvaWQiOiJiMDU2OGM0OS1hMjc2LTRlZWItOTAwMC02NTU1YzBiYzM4MDEiLCJyaCI6IjAuQVF3QW1PUUNOalQ5SGtxbUc3UmpuTzZ2X1NiSHBaTV9tSXhPb3pEeHMwNDlaMUlNQUxnLiIsInN1YiI6ImdFYVM1WUNxR1pCTHpKQnNZdWI0bHdfTm1uZlBNT3M5djhuQUU4dU9MaVEiLCJ0aWQiOiIzNjAyZTQ5OC1mZDM0LTRhMWUtYTYxYi1iNDYzOWNlZWFmZmQiLCJ1bmlxdWVfbmFtZSI6Im1lQG1rZW5hc2hvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoibWVAbWtlbmFzaG90bWFpbC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJrV0FxaTBmRUIwNnJ2RG15LUs1SkFBIiwidmVyIjoiMS4wIn0.y7oNvWn_3I2C79MQYSIQR3XgYrKddmTmw6ZyL6MlVYB1cxLLikVk4qAnn7EXKDtB3UI_mJwYz2Km2shZKZoQYWKIyCi_gK8E3XJeQxQheiqfd1xbnks94vFAbQOat1QF2jvthrua6K4bncj5xkeqKcd8c4GqosXNxzpeTZ75jg8htcYk-7sct08bU8yFh8O4FFKKjWbw0OyNk088_O5XweJAHvQycrC5ROz8wznt31oZATAmfvwdnFpoJXNWUy09VZjCYdnHoj9hnMHPrhQmgvZGio7DN0rR_MubDGlpkSNUTyLa50NNkm9OzXykYZ75MFuBHMrmzPlC6C8JnVn8yQ";
} else if (process.env.NODE_ENV === "development") {
  authorizationHeader = `Bearer ${getToken()}`;
  console.log("Copy this token to use in end to end test or in Swagger");
  console.log(authorizationHeader);
} else {
  authorizationHeader = `Bearer ${getToken()}`;
}
http.defaults.headers.common.Authorization = authorizationHeader;
export default http;
